title: "twohalv.es"
description: "A collection of writing."

url: "https://twohalv.es"

markdown: kramdown

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - favourite-ratio-server/
