title: "twohalv.es"
description: "A collection of writing."

url: "https://twohalv.es"

markdown: kramdown

include:
  - _pages

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
